# elasticsearch
ResetES = false
ESAddresses = ["http://localhost:9200"]
IndexName = "text"
# mecab
MecabDir = "/usr/lib/x86_64-linux-gnu/mecab/dic"
# bulk
BulkSourceDir = "/opt/ftb/bulk"
BulkWorkerNum = 4
BulkESUnitNum = 5000
IsBulkSubdir = true
AbortOnError = false
# cache
CacheSize = 0x40000000 # 2^30 = 1GB
